# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: deploy via ssh commands
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd reactjs-weekly-timetable
            git pull
            docker build -t rwtimetable --build-arg REACT_APP_BACKEND_URL=http://md.tru.io:8125 .
            docker stop rwtimetable || true
            docker run --rm -dp 3000:80 --name rwtimetable rwtimetable
            cd backend
            docker build -t wtapi .
            docker stop wtapi || true
            docker run --rm -dp 8125:8125 -v $PWD/store:/app/store --name wtapi wtapi
          host: md.tru.io
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
          
